"""OpenSCAD emitter for Step 1 panel assemblies."""

from __future__ import annotations

from typing import Iterable, List

from openscad_step1.contracts import PanelInstance


def _fmt_num(value: float) -> str:
    text = f"{float(value):.6f}"
    text = text.rstrip("0").rstrip(".")
    return text if text else "0"


def _fmt_vec(values: Iterable[float]) -> str:
    return "[" + ", ".join(_fmt_num(v) for v in values) + "]"


def _fmt_points(points: List[tuple[float, float]]) -> str:
    return "[" + ", ".join(_fmt_vec((x, y)) for x, y in points) + "]"


def render_openscad(
    *,
    panels: List[PanelInstance],
    material_thickness_mm: float,
    design_name: str,
) -> str:
    lines: List[str] = []
    lines.append("// Generated by openscad_step1 (clean-slate pipeline)")
    lines.append(f'// Design: "{design_name}"')
    lines.append("")
    lines.append(f"material_thickness = {_fmt_num(material_thickness_mm)};")
    lines.append("global_xy_scale = 1.0;")
    lines.append("$fn = 64;")
    lines.append("")

    for idx, panel in enumerate(panels):
        lines.append(f"module panel_2d_{idx}(s=1.0) {{")
        lines.append("  scale([s, s])")
        lines.append("  difference() {")
        lines.append(f"    polygon(points={_fmt_points(panel.outline_2d)});")
        for hole in panel.holes_2d:
            lines.append(f"    polygon(points={_fmt_points(hole)});")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    for idx, panel in enumerate(panels):
        matrix = [
            [panel.basis_u[0], panel.basis_v[0], panel.basis_n[0], panel.origin_3d[0]],
            [panel.basis_u[1], panel.basis_v[1], panel.basis_n[1], panel.origin_3d[1]],
            [panel.basis_u[2], panel.basis_v[2], panel.basis_n[2], panel.origin_3d[2]],
            [0.0, 0.0, 0.0, 1.0],
        ]
        lines.append(f"module panel_instance_{idx}() {{")
        lines.append("  multmatrix(m=[")
        lines.append(f"    {_fmt_vec(matrix[0])},")
        lines.append(f"    {_fmt_vec(matrix[1])},")
        lines.append(f"    {_fmt_vec(matrix[2])},")
        lines.append(f"    {_fmt_vec(matrix[3])}")
        lines.append("  ])")
        lines.append(
            "  linear_extrude(height=material_thickness, center=false, convexity=10)"
        )
        lines.append(f"    panel_2d_{idx}(global_xy_scale);")
        lines.append("}")
        lines.append("")

    lines.append("module assembled_panels() {")
    lines.append("  union() {")
    for idx, panel in enumerate(panels):
        lines.append(
            f"    // {panel.panel_id} from {', '.join(panel.source_candidate_ids)}"
        )
        lines.append(f"    panel_instance_{idx}();")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("assembled_panels();")
    lines.append("")
    return "\n".join(lines)
